# kubernetes-manifests/public-ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-api-ingress # Cambiamos el nombre para m√°s claridad
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
        - path: /auth
          pathType: Prefix
          backend:
            service:
              name: ms-auth-service
              port:
                number: 4000
        - path: /tutorias 
          pathType: Prefix
          backend:
            service:
              name: ms-tutorias-service
              port:
                number: 3000